version: '3.7'
services:
    gateway:
        restart: unless-stopped
        build:
            context: ./
            dockerfile: docker/development/gateway/Dockerfile
        ports:
            - 8080:80
            - 8081:81
        volumes:
            - ./docker/development/gateway/conf.d/:/etc/nginx/conf.d/
            - ./docker/development/gateway/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - frontend-nginx
            - backend-nginx


    frontend-nginx:
        restart: unless-stopped
        build:
            context: ./
            dockerfile: frontend/docker/development/nginx/Dockerfile
        volumes:
            - ./frontend:/var/www
            - ./frontend/docker/development/nginx/conf.d/:/etc/nginx/conf.d/
            - ./frontend/docker/development/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./frontend/docker/development/logs:/var/log/nginx/


    frontend-npm:
        build:
            context: ./
            dockerfile: frontend/docker/development/npm/Dockerfile
        volumes:
            - ./frontend:/var/www
        tty: true
        restart: unless-stopped
        ports:
          - 3000:8080


    backend-nginx:
        restart: unless-stopped
        build:
            context: ./
            dockerfile: backend/docker/development/nginx/Dockerfile
        volumes:
            - ./backend:/var/www
            - ./backend/docker/development/nginx/conf.d/:/etc/nginx/conf.d/
            - ./backend/docker/development/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./backend/docker/development/logs:/var/log/nginx/

    backend-mysql:
        image: mysql:8.0
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=rahman
            - MYSQL_PASSWORD=rahman
            - MYSQL_DATABASE=app
        volumes:
            - ./backend/docker/development/running/mysql:/var/lib/mysql/
        ports:
            - "33006:3306"


    backend-php-cli:
        build:
            context: ./
            dockerfile: backend/docker/development/php-cli/Dockerfile
            args:
                WWWUSER: ${USER}
        user: ${USER}
        tty: true
        volumes:
            - ./backend:/var/www/


    backend-php-fpm:
        build:
            context: ./
            dockerfile: backend/docker/development/php-fpm/Dockerfile
            args:
                WWWUSER: ${USER}
        user: ${USER}
        volumes:
            - ./backend:/var/www/
            - ./backend/docker/development/logs/:/var/log/php-fpm
            - ./backend/docker/development/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
        restart: unless-stopped
        depends_on:
            - backend-nginx
            - backend-mysql
        extra_hosts:
            - "host.docker.internal:host-gateway"

    backend-redis:
        image: redis
